services:
  frontend:
    image: ghcr.io/thearithhoul/dlink-frontend:latest
    container_name: dlink-frontend
    ports:
      - "5173:80"
    networks:
      - backend

networks:
  backend:
    external: true
    name: backend
